'use strict';
const $=s=>document.querySelector(s);
let total=25*60,remaining=total,deadline=0,running=false;
let tags=['Estudo','Trabalho','Pessoal'],selected='Estudo';
const tasks=Array.from({length:3},()=>({text:'',done:false}));
function format(n){return [Math.floor(n/60),n%60].map(v=>String(v).padStart(2,'0'));}
function draw(){const [m,s]=format(remaining);$('#clock').classList.toggle('long-time',m.length>2);$('#clock').innerHTML=m+'<span>:</span>'+s;$('#clock').setAttribute('aria-label',`${m} minutos e ${s} segundos restantes`);$('#elapsed').style.width=((total-remaining)/total*100)+'%';document.title=running?`${m}:${s} — tria`:'tria — três tarefas. um tempo.';}
function controls(){ $('#toggle span').textContent=running?'Pausar':remaining<total&&remaining>0?'Continuar':'Iniciar';$('#toggle svg').innerHTML=running?'<path d="M7 5h4v14H7zm7 0h4v14h-4z"/>':'<path d="m9 5 11 7-11 7z"/>';document.querySelectorAll('.duration button').forEach(b=>b.disabled=running);$('#minutes').disabled=running;$('#custom-form button').disabled=running;}
function tick(){if(!running)return;remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(remaining===0){running=false;$('#status').textContent='Tempo concluído. Respire.';controls();}draw();}
$('#toggle').onclick=()=>{if(running){tick();running=false;$('#status').textContent=remaining?'Uma pausa. Tudo bem.':'Tempo concluído. Respire.';}else{if(!remaining)remaining=total;deadline=Date.now()+remaining*1000;running=true;$('#status').textContent='Uma coisa de cada vez.';$('#custom-form').hidden=true;$('#custom').setAttribute('aria-expanded','false');}controls();draw();};
$('#reset').onclick=()=>{running=false;remaining=total;$('#status').textContent='Tudo no seu tempo';controls();draw();};
function duration(minutes){running=false;total=minutes*60;remaining=total;document.querySelectorAll('.duration-choice').forEach(b=>{const active=Number(b.dataset.min)===minutes;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$('#custom').classList.toggle('active',![25,45,60].includes(minutes));$('#status').textContent='Tudo no seu tempo';controls();draw();}
document.querySelectorAll('.duration-choice').forEach(b=>b.onclick=()=>duration(Number(b.dataset.min)));
$('#custom').onclick=()=>{$('#custom-form').hidden=!$('#custom-form').hidden;$('#custom').setAttribute('aria-expanded',String(!$('#custom-form').hidden));if(!$('#custom-form').hidden)$('#minutes').focus();};
$('#custom-form').onsubmit=e=>{e.preventDefault();const n=Number($('#minutes').value);if(!running&&Number.isInteger(n)&&n>=1&&n<=180){duration(n);$('#custom-form').hidden=true;$('#custom').setAttribute('aria-expanded','false');$('#custom').focus();}};
function renderTags(){$('#tags').replaceChildren();tags.forEach(tag=>{const b=document.createElement('button');b.type='button';b.textContent=tag;b.className='tag'+(selected===tag?' selected':'');b.setAttribute('aria-pressed',String(selected===tag));b.onclick=()=>{selected=selected===tag?'':tag;renderTags();};$('#tags').append(b);});}
$('#new-tag').onclick=()=>{$('#tag-form').hidden=!$('#tag-form').hidden;$('#new-tag').setAttribute('aria-expanded',String(!$('#tag-form').hidden));if(!$('#tag-form').hidden)$('#tag-name').focus();};
$('#tag-form').onsubmit=e=>{e.preventDefault();const v=$('#tag-name').value.trim();if(!v)return;const old=tags.find(t=>t.toLocaleLowerCase()===v.toLocaleLowerCase());if(!old&&tags.length>=12){$('#tag-feedback').textContent='Limite de 12 tags por sessão.';return;}if(!old)tags.push(v);selected=old||v;renderTags();$('#tag-name').value='';$('#tag-form').hidden=true;$('#new-tag').setAttribute('aria-expanded','false');$('#tag-feedback').textContent='';$('#new-tag').focus();};
function count(){const done=tasks.filter(t=>t.done&&t.text.trim()).length;$('#count').textContent=`${done} / 3`;$('#task-note').textContent=done===3?'O essencial está feito. Aproveite a pausa.':tasks.some(t=>t.text.trim())?'Uma de cada vez já é suficiente.':'O primeiro passo cabe em uma linha.';}
tasks.forEach((task,i)=>{const row=document.createElement('div');row.className='task-row';const check=document.createElement('input');check.type='checkbox';check.setAttribute('aria-label',`Concluir tarefa ${i+1}`);check.disabled=true;const input=document.createElement('input');input.className='task-text';input.type='text';input.maxLength=180;input.placeholder=['Qual é a primeira tarefa?','E depois?','Uma última coisa.'][i];input.setAttribute('aria-label',`Tarefa ${i+1}`);const del=document.createElement('button');del.className='delete';del.textContent='×';del.hidden=true;del.setAttribute('aria-label',`Apagar tarefa ${i+1}`);input.oninput=()=>{task.text=input.value;check.disabled=!task.text.trim();del.hidden=!task.text;if(check.disabled){task.done=false;check.checked=false;row.classList.remove('done');}count();};check.onchange=()=>{task.done=check.checked;row.classList.toggle('done',task.done);count();};del.onclick=()=>{task.text='';task.done=false;input.value='';check.checked=false;check.disabled=true;del.hidden=true;row.classList.remove('done');count();input.focus();};input.onkeydown=e=>{if(e.key==='Enter'){const next=document.querySelectorAll('.task-text')[i+1];if(next)next.focus();else input.blur();}};row.append(check,input,del);$('#task-list').append(row);});
setInterval(tick,250);document.addEventListener('visibilitychange',tick);renderTags();draw();
